### 1. 含义

async函数是Generator函数的语法糖。

```js
const fs = require('fs');

const readFile = function (fileName) {
  return new Promise(function (resolve, reject) {
    fs.readFile(fileName, function(error, data) {
      if (error) return reject(error);
      resolve(data);
    });
  });
};

//Generator函数的写法
const gen = function* () {
  const f1 = yield readFile('/etc/fstab');
  const f2 = yield readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
};

//async函数写法
const asyncReadFile = async function () {
  const f1 = await readFile('/etc/fstab');
  const f2 = await readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
};
```

注意：

- `async`函数调用直接执行了，Generator函数调用返回一个遍历器，需要`next`方法来执行
- **`async`函数的返回值是Promise对象**，而Generator函数的返回值是Iterator对象。

进一步说，`async`函数完全可以看作多个异步操作，包装成的一个Promise对象，而`await`命令就是内部`then`命令的语法糖。



### 2. 基本用法

**`async`函数返回一个Promise对象，可以使用`then`方法添加回调函数**。当函数执行的时候，一旦遇到`await`就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。

```js
async function getStockPriceByName(name) {
  const symbol = await getStockSymbol(name);
  const stockPrice = await getStockPrice(symbol);
  return stockPrice;
}

getStockPriceByName('goog').then(function (result) {
  console.log(result);
});
```

函数前面的`async`关键字，表明该函数内部有异步操作。调用该函数时，会立即返回一个`Promise`对象。

由于`async`函数返回的是 Promise 对象，可以作为`await`命令的参数。

```javascript
async function timeout(ms) {
  await new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function asyncPrint(value, ms) {
  await timeout(ms);
  console.log(value);
}

asyncPrint('hello world', 50);
```

#### async函数的使用形式

```javascript
// 函数声明
async function foo() {}

// 函数表达式
const foo = async function () {};

// 对象的方法
let obj = { async foo() {} };
obj.foo().then(...)

// Class 的方法
class Storage {
  constructor() {
    this.cachePromise = caches.open('avatars');
  }

  async getAvatar(name) {
    const cache = await this.cachePromise;
    return cache.match(`/avatars/${name}.jpg`);
  }
}

const storage = new Storage();
storage.getAvatar('jake').then(…);

// 箭头函数
const foo = async () => {};
```



### 3. 语法

难点在错误处理机制

#### 返回Promise对象

**`async`函数返回一个Promise对象。**

`async`函数内部`return`语句返回的值，会成为`then`方法回调函数的参数。

```javascript
async function f() {
  return 'hello world';
}

f().then(v => console.log(v))
// "hello world"
```

**`async`函数内部抛出错误，会导致返回的 Promise 对象变为`reject`状态。抛出的错误对象会被`catch`方法回调函数接收到。**

```javascript
async function f() {
  throw new Error('出错了');
}

f().then(
  v => console.log(v),
  e => console.log(e)
)
// Error: 出错了
```

#### Promise对象的状态变化

`async`函数返回的Promise对象，必须等到内部所有`await`命令后面的Promise对象执行完，才会发生状态改变，除非遇到`return`语句或者抛出错误。也就是说，只有`async`函数内部的异步操作执行完，才会执行`then`方法指定的回调函数。

#### await命令

1. 正常情况下，`await`命令后面是一个Promise对象，返回该对象的结果。如果不是Promise对象，就直接返回对应的值。

```js
async function f() {
    //等同于 return 123
    return await 123;
}
//函数返回的是一个Promise对象
f().then(v => console.log(v))
```

2. 另一种情况是，`await`命令后面是一个`thenable`对象(即定义`then`方法的对象)，那么`await`会将其等同于Promise对象。因为定义了`then`方法，`await`会将其视为`Promise`处理。

```js
class Sleep {
  constructor(timeout) {
    this.timeout = timeout;
  }
  then(resolve, reject) {
    const startTime = Date.now();
    setTimeout(
      () => resolve(Date.now() - startTime),
      this.timeout
    );
  }
}
(async () => {
  const actualTime = await new Sleep(1000);
  console.log(actualTime);
})();
```

3. `await`命令后面的Promise对象如果变为`reject`状态，则`reject`的参数会被`catch`方法的回调函数接收到。

```javascript
async function f() {
  await Promise.reject('出错了');
}

f()
.then(v => console.log(v))
.catch(e => console.log(e))
// 出错了
```

4. 任何一个`await`语句后面的Promise对象变为`reject`状态，那么整个`async`函数都会中断执行。

```js
async function f() {
    await Promise.reject('出错了');	//状态为reject，下面都会中断
    await Promise.resolve(111);			//不会执行
}
```

5. 有时候即使异步操作失败，也不要中断后面的异步操作。

此时可以使用`try...catch`

```js
async function f() {
    try {
        await Promise.reject('出错了');
    } catch(e) {
    }
    //因为上面使用try catch捕获了异常，所以下面还是能执行
    return await Promise.resolve('hello world');	
}
f().then(v => console.log(v))
```

另一种方法是`await`后面的Promise对象再跟一个`catch`方法，处理前面可能出现的错误。

```js
async function f() {
    await Promise.reject('出错了')	
        .catch(e => console.log(e));	//出错了    在这一步就先捕获错误了，所以下面能执行下去了
    return await Promise.resolve(111);
}
f().then(v => console.log(v))	//111
```

#### 错误处理

如果`await`后面的异步操作出错，那么等同于`async`函数返回的Promise对象被`reject`。并且下面的代码不会再执行下去。

```js
async function f() {
    await new Promise((resolve, reject) => {
        throw new Error('出错了');
    });
}
fn()
.then(v => console.log(v))
.catch(e => console.log(e))		//出错了
```

防止出错的办法是：

1. 使用`try...catch`

```js
async function f() {
    try {	
        //只要有一个错误就能捕获
        await new Promise((resolve, reject) => {
            throw new Error('出错了');
        });
        await xxx;
    } catch(e) {
    }
    return await 111
}
```

2. 直接捕获Promise.reject对象

```js
async function f() {
    await Promise.reject('出错了')
   		.catch(e => console.log(e))		//因为这里捕获了，所以下面能够继续执行
    return await 111;
}
```

#### 注意点

1. `await`命令后面的`Promise`对象，运行结果可能是`rejected`，所以最好把`await`命令放在`try...catch`代码块中或者使用`.catch`捕获`Promise.reject`。

```js
//写法一
async function myFunction() {
    try {
        await somethingThatReturnsAPromise();
    } catch(err) {
        console.log(err)
    }
}
//另一种写法
async function myFunction() {
    await somethingThatReturnsAPromise()
    	.catch(err => console.log(err))
}
```

2. 多个`await`命令后面的异步操作，如果不存在继发关系，最好同时触发。

```js
let foo = await getFoo();
let bar = await getBar();
//改为

// 写法一
let [foo, bar] = await Promise.all([getFoo(), getBar()]);
// 写法二
let fooPromise = getFoo();
let barPromise = getBar();
let foo = await fooPromise;
let bar = await barPromise;
```

3. `await`命令只能用在async函数之中

4. `async`函数可以保留运行堆栈



### 4. async函数的实现原理

async函数的实现原理，就是将Generator函数和自动执行器，包含在一个函数中。

```javascript
async function fn(args) {
  // ...
}
// 等同于
function fn(args) {
  return spawn(function* () {	//spawn就是自动执行器  返回一个Promise对象
    // ...
  });
}
```

```javascript
function spawn(genF) {  //1.传入一个遍历器对象
  return new Promise(function(resolve, reject) { //4. 返回一个Promise对象
    const gen = genF();	
    function step(nextF) {  //2. 一个递归函数，直到遍历器对象的最后一个值
      let next;
      try {
        next = nextF();
      } catch(e) {
        return reject(e);
      }
      if(next.done) {	//2.1 如果是最后一个，则抛出
        return resolve(next.value);
      }
      Promise.resolve(next.value).then(function(v) {	//2.2 不是最后一个则递归，知道最后一个
        step(function() { return gen.next(v); });
      }, function(e) {
        step(function() { return gen.throw(e); });
      });
    }
    step(function() { return gen.next(undefined); });	//3. 执行函数
  });
}
```



### 5. 其他异步处理方法的比较

1. Promise
2. Generator
3. async

假定某个 DOM 元素上面，部署了一系列的动画，前一个动画结束，才能开始后一个。如果当中有一个动画出错，就不再往下执行，返回上一个成功执行的动画的返回值。

1. 首先是Promise的写法

```javascript
function chainAnimationsPromise(elem, animations) {
    // 变量ret用来保存上一个动画的返回值
    let ret = null; 
    // 新建一个空的Promise
    let p = Promise.resolve();
    // 使用then方法，添加所有动画
    for(let anim of animations) {   
        //如果这里将let换成var，那么因为异步的原因不能获得每个anim，直接是最后一个anim值
        p = p.then(val => {	//异步
            ret = val;
            return anim(elem)
        })
    }
    // 返回一个部署了错误捕捉机制的Promise    上面出错就能捕获到，然后不会继续执行下去了，直接执行这里
    return p.catch(function(e) {
        /* 忽略错误，继续执行 */
    }).then(function() {
        return ret;		//捕获后跳出上一个状态
    });
}
```

2. Generator的写法

```js
function chainAnimationsPromise(elem, animations) {
    return spawn(function* () {
        let ret = null;
        try {
            for(let anim of animations) {
               ret = yield anim(elem)
            }
        } catch(e) {
            /* 忽略错误，继续执行 */
        }
        return ret;
    })
}
```

这个写法的问题在于，必须有一个任务运行器，自动执行 Generator 函数，上面代码的`spawn`函数就是自动执行器，它返回一个 Promise 对象，而且必须保证`yield`语句后面的表达式，必须返回一个 Promise。

3. 最后是 async 函数的写法

```javascript
async function chainAnimationsAsync(elem, animations) {
  let ret = null;
  try {
    for(let anim of animations) {
      ret = await anim(elem);
    }
  } catch(e) {
    /* 忽略错误，继续执行 */
  }
  return ret;
}
```



### 6. 实例：按顺序完成异步操作

Promise写法

```javascript
function logInOrder(urls) {
  // 远程读取所有URL
  const textPromises = urls.map(url => {
    return fetch(url).then(response => response.text());
  });

  // 按次序输出
  textPromises.reduce((chain, textPromise) => {
    return chain.then(() => textPromise)
      .then(text => console.log(text));
  }, Promise.resolve());
}
```

改成async的写法

```javascript
async function logInOrder(urls) {
  for (const url of urls) {
    const response = await fetch(url);
    console.log(await response.text());
  }
}
```

上面代码确实大大简化，问题是所有远程操作都是继发。只有前一个 URL 返回结果，才会去读取下一个 URL，这样做效率很差，非常浪费时间。我们需要的是并发发出远程请求。

```javascript
async function logInOrder(urls) {
  // 并发读取远程URL
  const textPromises = urls.map(async url => {	//注意这里是async函数作为参数， 这里是并发
    const response = await fetch(url);
    return response.text();
  });

  // 按次序输出
  for (const textPromise of textPromises) {		//这里是继发
    console.log(await textPromise);
  }
}
```

虽然`map`方法的参数是`async`函数，但它是并发执行的，**因为只有`async`函数内部是继发执行，外部不受影响**。后面的`for..of`循环内部使用了`await`，因此实现了按顺序输出。




### 7. 异步遍历器

《遍历器》一章说过，Iterator 接口是一种数据遍历的协议，只要调用遍历器对象的`next`方法，就会得到一个对象，表示当前遍历指针所在的那个位置的信息。`next`方法返回的对象的结构是`{value, done}`，其中`value`表示当前的数据的值，`done`是一个布尔值，表示遍历是否结束。

`next`方法必须是同步的，只要调用就必须立刻返回值。也就是说，一旦执行`next`方法，就必须同步地得到`value`和`done`这两个属性。如果遍历指针正好指向同步操作，当然没有问题，但对于异步操作，就不太合适了。

目前的解决方法是，Generator 函数里面的异步操作，返回一个 Thunk 函数或者 Promise 对象，即`value`属性是一个 Thunk 函数或者 Promise 对象，等待以后返回真正的值，而`done`属性则还是同步产生的。

#### 异步遍历的接口

异步遍历器的最大的语法特点，就是调用遍历器的`next`方法，**返回的是一个 Promise 对象**。

```javascript
asyncIterator
  .next()
  .then(  //回调函数的参数，则是一个具有value和done两个属性的对象
    ({ value, done }) => /* ... */
  );
```

我们知道，一个对象的同步遍历器的接口，部署在`Symbol.iterator`属性上面。同样地，对象的异步遍历器接口，部署在`Symbol.asyncIterator`属性上面。不管是什么样的对象，只要它的`Symbol.asyncIterator`属性有值，就表示应该对它进行异步遍历。

```javascript
const asyncIterable = createAsyncIterable(['a', 'b']);
const asyncIterator = asyncIterable[Symbol.asyncIterator]();

asyncIterator
.next()
.then(iterResult1 => {
  console.log(iterResult1); // { value: 'a', done: false }
  return asyncIterator.next();
})
.then(iterResult2 => {
  console.log(iterResult2); // { value: 'b', done: false }
  return asyncIterator.next();
})
.then(iterResult3 => {
  console.log(iterResult3); // { value: undefined, done: true }
});
```

由于异步遍历器的`next`方法，返回的是一个 Promise 对象。因此，可以把它放在`await`命令后面。

```javascript
async function f() {
  const asyncIterable = createAsyncIterable(['a', 'b']);
  const asyncIterator = asyncIterable[Symbol.asyncIterator]();
  console.log(await asyncIterator.next());
  // { value: 'a', done: false }
  console.log(await asyncIterator.next());
  // { value: 'b', done: false }
  console.log(await asyncIterator.next());
  // { value: undefined, done: true }
}
```

#### for await...of

前面介绍过，`for...of`循环用于遍历同步的 Iterator 接口。新引入的`for await...of`循环，则是用于遍历异步的 Iterator 接口。

```javascript
async function f() {
  for await (const x of createAsyncIterable(['a', 'b'])) {
    console.log(x);
  }
}
// a
// b
```

上面代码中，`createAsyncIterable()`返回一个拥有异步遍历器接口的对象，`for...of`循环自动调用这个对象的异步遍历器的`next`方法，会得到一个 Promise 对象。`await`用来处理这个 Promise 对象，一旦`resolve`，就把得到的值（`x`）传入`for...of`的循环体。

如果`next`方法返回的 Promise 对象被`reject`，`for await...of`就会报错，要用`try...catch`捕捉。

```javascript
async function () {
  try {
    for await (const x of createRejectingIterable()) {
      console.log(x);
    }
  } catch (e) {
    console.error(e);
  }
}
```

注意，`for await...of`循环也可以用于同步遍历器。

```javascript
(async function () {
  for await (const x of ['a', 'b']) {
    console.log(x);
  }
})();
// a
// b
```

#### 异步 Generator 函数

就像 Generator 函数返回一个同步遍历器对象一样，异步 Generator 函数的作用，是返回一个异步遍历器对象。

```javascript
async function* gen() {
  yield 'hello';
}
const genObj = gen();
genObj.next().then(x => console.log(x));
// { value: 'hello', done: false }
```

执行后返回一个异步 Iterator 对象。**对该对象调用`next`方法，返回一个 Promise 对象。**

异步遍历器的设计目的之一，就是 Generator 函数处理同步操作和异步操作时，能够使用同一套接口。

```javascript
// 同步 Generator 函数
function* map(iterable, func) {
  const iter = iterable[Symbol.iterator]();
  while (true) {
    const {value, done} = iter.next();
    if (done) break;
    yield func(value);
  }
}

// 异步 Generator 函数
async function* map(iterable, func) {
  const iter = iterable[Symbol.asyncIterator]();
  while (true) {
    const {value, done} = await iter.next();
    if (done) break;
    yield func(value);
  }
}
```

异步 Generator 函数内部，能够同时使用`await`和`yield`命令。可以这样理解，`await`命令用于将外部操作产生的值输入函数内部，`yield`命令用于将函数内部的值输出。

异步 Generator 函数可以与`for await...of`循环结合起来使用。

```javascript
async function* prefixLines(asyncIterable) {
  for await (const line of asyncIterable) {		//异步Generator函数通过for of遍历返回一个个Promise堆栈，通过await取得值
    yield '> ' + line;			//在异步Generator函数中yield xx 会被自动包装成Promise对象
  }
}
```

像上面那个例子那样，因为在异步Generator函数中，所以`yield`命令后面是一个字符串，会被自动包装成一个 Promise 对象。

如果异步 Generator 函数抛出错误，会导致 Promise 对象的状态变为`reject`，然后抛出的错误被`catch`方法捕获。

```javascript
async function* asyncGenerator() {
  throw new Error('Problem!');
}

asyncGenerator()
.next()
.catch(err => console.log(err)); // Error: Problem!
```

异步 Generator 函数也可以通过`next`方法的参数，接收外部传入的数据。

```javascript
const writer = openFile('someFile.txt');
writer.next('hello'); // 立即执行
writer.next('world'); // 立即执行
await writer.return(); // 等待写入结束
```

#### yield* 语句

`yield*`语句也可以跟一个异步遍历器。

```javascript
async function* gen1() {
    yield 'a';
    yield 'b';
    return 2;
}

async function* gen2() {
    // result 最终会等于 2
    const result = yield* gen1();
    console.log(result)	//2， 执行第三次next()方法才输出2
}
let g2 = gen2();
g2.next()
g2.next()
g2.next()		
```

上面代码中，`gen2`函数里面的`result`变量，最后的值是`2`。

与同步 Generator 函数一样，`for await...of`循环会展开`yield*`。

```javascript
(async function () {
  for await (const x of gen2()) {
    console.log(x);
  }
})();
// a
// b
```